# Fix up rss feed link

[[redirects]]
  from = "/thoughts/feed"
  to = "/thoughts/feed.rss"


# redirect search to duckduckgo

[[redirects]]
  from = "/search"
  to = "https://duckduckgo.com/?q=:term+site%3Adtott.com"
  query = {term = ":term"}

[[redirects]]
  from = "/thoughts/search"
  to = "/xsearch/:q"
  query = {q = ":q"}

[[redirects]]
  from = "/xsearch/tags:*"
  to = "/tags/:splat"

[[redirects]]
  from = "/thoughts/search"
  to = "/thoughts"

[[redirects]]
  from = "/xsearch/*"
  to = "https://duckduckgo.com/?q=:splat+site%3Adtott.com"


# Fix up some whoopsies

[[redirects]]
  from = "/thoughts/styling-react-components-talk"
  to = "/thoughts/2020/02/12/styling-react-components-talk"

[[redirects]]
  from = "/thoughts/2007/09/10/css-tips-1-use-a-reset"
  to = "/thoughts/2007/09/10/css-tip-1-use-a-reset"


# add gatsby cache build plugin
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
